# Generated by Django 5.1.3 on 2025-01-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recentwork",
            name="description",
            field=models.TextField(
                default="No description available", verbose_name="About project"
            ),
            preserve_default=False,
        ),
        
        migrations.AddField(
            model_name="service",
            name="icon",
            field=models.ImageField(default="no icon", upload_to="services"),
            preserve_default=False,
        ),
    ]
