# Generated by Django 5.1.3 on 2025-01-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_recentwork_description_service_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="recentwork",
            name="project_url",
            field=models.TextField(default="no url", verbose_name="URL project"),
            preserve_default=False,
        ),
    ]
